services:
  ai-database:
    image: pgvector/pgvector:pg16
    container_name: rag-llm-database
    healthcheck:
      test: pg_is_ready -U $POSTGRES_USER
      start_interval: 1s
      start_period: 5s
      interval: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - ./data:/var/lib/postgresql/data